### ISSUE TITLE
The type hint of the parameter r of EntropyHub._FuzzEn.FuzzEn is confusing.

### ISSUE THREAD

**Issue by rexjz** [MattWillFlood/EntropyHub#1]
![image](https://user-images.githubusercontent.com/54502639/206727960-86bec25f-3a4e-46af-a808-de5b8b6580c8.png)
If pass a tuple as parameter r, the type hint of the second element is int, but it should be float.
This is because the type hint is inferred from the default value of r.
definition of EntropyHub._FuzzEn.FuzzEn:
![image](https://user-images.githubusercontent.com/54502639/206728362-2c4b3859-0128-4a06-9c60-3479357d4e6e.png)

**Comment by MattWillFlood** [comment]
Hi @rexjz 
Thank you so much for bringing this to my attention. 
I will update this hint and the description in the [user guide](https://github.com/MattWillFlood/EntropyHub/blob/main/EntropyHub%20Guide.pdf) as soon as I can.
_Just to be clear, the code still runs whether you enter a float or int :)_ 
Thanks again!
M

**Comment by MattWillFlood** [comment]
This has been fixed in the latest release (v1.0) :)
