### ISSUE TITLE
SampEn fails using large arrays

### ISSUE THREAD

**Issue by shrimpKing-png** [MattWillFlood/EntropyHub#10]
Using an array of length 107239 I get an error code Exit code 137 interrupted by signal 9:SIGKILL

The code works fine for my datasets of smaller length but this one sample seems to keep giving me errors.

**Comment by MattWillFlood** [comment]
Hi @AceKijani ,
Can you please provide more info?
- Are you using MatLab, Python or Julia?
- What number type is your data (single/double precision, integers)?
- What SampEn parameters are you using (m, tau, r, Vcp)?

Thanks
