### ISSUE TITLE
What is the difference between Multivariate Entropies and Bidimensional Entropies? I have to find the entropy for EEG signals with shape (Channels, Timepoints). Which one would be better? 

### ISSUE THREAD

**Issue by AashishKhilnani** [MattWillFlood/EntropyHub#12]

**Comment by MattWillFlood** [comment]
Hi @AashishKhilnani 🙂,

If you are working with EEG data 🧠 , then the multivariate entropies are the methods you should use 👍🏼 
You should pass your data in the form of an NxM matrix, where N (rows) is number of EEG samples and M (columns) are the EEG channels.

Bidimensional entropies are used for univariate data in the form of a 2D matrix (e.g. image data), not multivariate data.

Hope this helps! 👍🏼 🙃

**Comment by AashishKhilnani** [comment]
Thanks for the help!
