### ISSUE TITLE
BubbEn output interpretation 

### ISSUE THREAD

**Issue by ejc043** [MattWillFlood/EntropyHub#6]
Thank you for this wonderful package!! 
For the ```BubbEn``` function for some values of ```m```, there are multiple outputs of the estimated bubble entropy ```Bubb```. How can we interpret the multiple outputs? Would this be the average?
Thank you!

**Comment by MattWillFlood** [comment]
Hi @ejc043 !

Thank you for your question : )
`BubbEn()` returns two variables: 
1. `Bubb` - **the bubble entropy estimates**
The number of values returned in `Bubb` corresponds to the embedding dimension (`m`) used to estimate Bubble entropy.
`Bubb` will **always** have _**m-1**_ values, so if _m=2_, `Bubb` will have 1 value; if _m=5_, `Bubb` will have 4 values.
Therefore, each value in `Bubb` is the bubble entropy estimate calculated using **each dimension from** `2:m`.
If you use _m>2_, the last value in `Bubb` will be the value for that `m`. 
    > So if you call:    `Bubb, H = BubbEn(Signal, m= 7)`
 `Bubb[6]` will be the bubble entropy estimate for _m==7_, 
 `Bubb[4]` will be the bubble entropy estimate for _m==5_, 
 `Bubb[1]` will be the bubble entropy estimate for _m==2_.

 In most cases, you just want the last value in `Bubb` in your analysis.

2. `H`  - **the conditional Renyi entropy estimates**
Similarly, the number of values returned in `H` also corresponds to `m`.
`H` will always have _**m+1**_ values, corresponding to the conditional Renyi entropy estimates for each value from `1:m+1`.
**Note, the first value of `H` will always be zero.**

For more info, see the paper by [Manis et al.](https://ieeexplore.ieee.org/document/7842617)

Apologies for this confusion.
I will try to update the [EntropyHub Guide](https://github.com/MattWillFlood/EntropyHub/blob/main/EntropyHub%20Guide.pdf) and the relative documentation to make this more clear.

I hope this helps!
Thanks,
Matt

**Comment by ejc043** [comment]
Hi @MattWillFlood,
Thank you for the fast response! Yes that makes sense.
Thank you!!
Eunice
