### ISSUE TITLE
How to calculate ApEn via EntropyHub with data in shape (10000, )?

### ISSUE THREAD

**Issue by Ildaron** [MattWillFlood/EntropyHub#7]
Hello, I have the next script for data with length - (10000, )

"
import EntropyHub as EH

X = my_data
print((X.shape) # (10000, ) 
Mobj = EH.MSobject('XApEn', m = 2, tau = 2, r = 0.5)
MSx, _ = EH.cXMSEn(X, Mobj, Scales = 3, RadNew = 1)
"

My error - AssertionError: Sig:   must be a 2-column or 2-row numpy array
Why I should make shape with the from (5000, 2) ?

**Comment by MattWillFlood** [comment]
Hi @Ildaron,

The functions cXMSEn and XApEn are cross-entropy functions, so they require two (equal length) univariate time series as inputs. 
If you want to calculate composite multiscale entropy of a single time series with approximate entropy (ApEn) as the base method, then you should use _cMSEn()_ and _ApEn()_ respectively like so:

```
import EntropyHub as EH

X = my_data
print((X.shape) # (10000, )
Mobj = EH.MSobject('ApEn', m = 2, tau = 2, r = 0.5)
MSx, _ = EH.cMSEn(X, Mobj, Scales = 3, RadNew = 1)`
```

Hope this helps! :)
Matt

**Comment by Ildaron** [comment]
Hi @MattWillFlood thank you so much!!!
