### ISSUE TITLE
Bug in _DispEn2D.py

### ISSUE THREAD

**Issue by YingFan-Chen** [MattWillFlood/EntropyHub#8]
![image](https://github.com/MattWillFlood/EntropyHub/assets/103208843/6b924dc9-46ad-42c2-afd4-22167862c97c)

I think 'Mat' should be replaced by 'Zi' in line 127 of above screenshot, cause 'Zi' matrix is the one after mapping in dispersion entropy.

**Comment by MattWillFlood** [comment]
Dear @YingFan-Chen 

Thank you so much for spotting this bug! 
This is very helpful :)

This correction will be included in the next package release which is due very soon!

**Comment by MattWillFlood** [comment]
This issue has been fixed in the latest release (v1.0) :)
