### ISSUE TITLE
Unable to Import LIbrary

### ISSUE THREAD

**Issue by AashishKhilnani** [MattWillFlood/EntropyHub#9]
Hi. 
I am using Python 3.9.12 with Anaconda.
I installed EntropyHub and then tried to import. I am not able to import the library. I am attaching the screenshot. 
Please look into it.

<img width="644" alt="Screenshot 2024-04-23 102701" src="https://github.com/MattWillFlood/EntropyHub/assets/95607785/f01dbcc6-b5ac-4128-8f00-9f888d650076">

**Comment by sajtarius** [comment]
I am also having the same issue too. If you are not going to use the update function, then you can try to use the older version of EntropyHub. Or you can manually move the library or functions where you store all the libraries.

**Comment by MattWillFlood** [comment]
This problem should be fixed with the new release of [EntropyHub (v2.0) on PyPi](https://pypi.org/project/EntropyHub/) 

[See here for more info](https://github.com/MattWillFlood/EntropyHub/issues/2#issuecomment-2076018955)
